<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
 
$_config = $this->helper('Sm\Market\Helper\Data');
$footerStyle = $_config->getThemeLayout('footer_style');

include (dirname(__FILE__).'/footer-style/'.$footerStyle.'.phtml');

?>
<script type="text/javascript">
var $zoho= $zoho || {salesiq:{values:{},ready:function(){}}};var d=document;s=d.createElement("script");s.type="text/javascript";
s.defer=true;s.src="https://salesiq.zoho.com/lovebabyproducts/float.ls?embedname=lovebabyproducts";
t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);
</script>
